apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-hw-app-config
data:
  datasourceUrl: "jdbc:postgresql://{{ .Release.Name }}-postgres-svc:5432/postgres"
  artemisUrl   : "tcp://{{ .Release.Name }}-jms-broke-svc:61616"
  accountUrl   : "http://{{ .Release.Name }}-hw-service-billing:80"