apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hw-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"

spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.base.host }}
      http:
        paths:
        - path: /api/register
          pathType: {{ .Values.base.pathType }}
          backend:
            service:
              name: {{ .Release.Name }}-hw-service-billing
              port:
                number: {{ .Values.base.port }}
        - path: /api/refill/
          pathType: {{ .Values.base.pathType }}
          backend:
            service:
              name: {{ .Release.Name }}-hw-service-billing
              port:
                number: {{ .Values.base.port }}
        - path: /api/create-order
          pathType: {{ .Values.base.pathType }}
          backend:
            service:
              name: {{ .Release.Name }}-hw-service-order
              port:
                number: {{ .Values.base.port }}
        - path: /api/account
          pathType: {{ .Values.base.pathType }}
          backend:
            service:
              name: {{ .Release.Name }}-hw-service-billing
              port:
                number: {{ .Values.base.port }}
        - path: /api/notification
          pathType: {{ .Values.base.pathType }}
          backend:
            service:
              name: {{ .Release.Name }}-hw-service-notice
              port:
                number: {{ .Values.base.port }}