apiVersion: v2
name: homework-8-infra
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: rabbitmq
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 12.2.2