version: "3"

services:
  postgres:
    image: postgres:11
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=profile_user
      - POSTGRES_PASSWORD=profile_pass
      - POSTGRES_DB=profile