apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  reload: RmFsc2U=
  dbuser: ZGJ1c2Vy
  dbpass: ZGJwYXNz
  dbhost: cG9zdGdyZXMtc2VydmljZQ==
  dbport: NTQzMg==
  dbname: YXBwZGI=
  db_max_connections: MTA=
  dc_pool_recycle: NjA=
