version: "3"

services:
  postgres:
    image: postgres:11
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=delivery_user
      - POSTGRES_PASSWORD=delivery_pass
      - POSTGRES_DB=delivery