apiVersion: v1
kind: Service
metadata:
 name: "{{ .Chart.Name }}-{{ .Release.Name }}-service"
spec:
  selector:
    app: "{{ .Chart.Name }}-{{ .Release.Name }}"
  ports:
  - port: {{ .Values.service.port}}
    protocol: TCP
    targetPort: {{ .Values.api.port}}
  type: NodePort
