version: "3"

services:
  postgres:
    image: postgres:11
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=payment_user
      - POSTGRES_PASSWORD=payment_pass
      - POSTGRES_DB=payment