apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name}}-service
  labels:
    app: {{ .Chart.Name}}
spec:
  selector:
    app: {{ .Chart.Name}}
  ports:
  - port: {{ .Values.port }}
    targetPort: {{ .Values.port }}
  type: NodePort