namespace: ms-delivery

secrets:
  reload: False
  api_port: 8000
  consumer_port: 8001
  dbuser: msdelivery-db-user
  dbpass: msdelivery-db-pass
  dbhost: postgres-service
  dbport: 5432
  dbname: delivery
  db_max_connections: 10
  dc_pool_recycle: 60
  rabbitmq_user: rmuser
  rabbitmq_pass: rmpass
  rabbitmq_host: rabbit-rabbitmq.rmq.svc.cluster.local
  rabbitmq_port: 5672
  order_state_changed_queue: order.state_changed
  order_products_reserved_queue: order.products_reserved
  order_products_backward_queue: order.products_backward
  

api:
  replicas: 1
  image: 
    repository: futureshaper/microservice-architecture-homeworks
    tag: homework8-ms-delivery-api
  imagePullPolicy: Always
  port: 8000
  containerEnv:
    RELOAD: reload
    API_PORT: api_port
    DB_USER: dbuser
    DB_PASS: dbpass
    DB_HOST: dbhost
    DB_PORT: dbport
    DB_NAME: dbname
    DB_MAX_CONNECTIONS: db_max_connections
    DC_POOL_RECYCLE: dc_pool_recycle
    RABBITMQ_USER: rabbitmq_user
    RABBITMQ_PASS: rabbitmq_pass
    RABBITMQ_HOST: rabbitmq_host
    RABBITMQ_PORT: rabbitmq_port
    ORDER_STATE_CHANGED_QUEUE: order_state_changed_queue
    ORDER_PRODUCTS_RESERVED_QUEUE: order_products_reserved_queue
    ORDER_PRODUCTS_BACKWARD_QUEUE: order_products_backward_queue
  migrationEnv:
    DB_USER: dbuser
    DB_PASS: dbpass
    DB_HOST: dbhost
    DB_PORT: dbport
    DB_NAME: dbname

consumer:
  replicas: 1
  image: 
    repository: futureshaper/microservice-architecture-homeworks
    tag: homework8-ms-delivery-consumer
  imagePullPolicy: Always
  port: 8001
  containerEnv:
    RELOAD: reload
    CONSUMER_PORT: consumer_port
    DB_USER: dbuser
    DB_PASS: dbpass
    DB_HOST: dbhost
    DB_PORT: dbport
    DB_NAME: dbname
    DB_MAX_CONNECTIONS: db_max_connections
    DC_POOL_RECYCLE: dc_pool_recycle
    RABBITMQ_USER: rabbitmq_user
    RABBITMQ_PASS: rabbitmq_pass
    RABBITMQ_HOST: rabbitmq_host
    RABBITMQ_PORT: rabbitmq_port
    ORDER_STATE_CHANGED_QUEUE: order_state_changed_queue
    ORDER_PRODUCTS_RESERVED_QUEUE: order_products_reserved_queue
    ORDER_PRODUCTS_BACKWARD_QUEUE: order_products_backward_queue

service:
  ports:
    - name: api
      port: 9000
      targetPort: 8000

postgres:
  namespace: ms-delivery
  env:
    POSTGRES_USER: msdelivery-db-user
    POSTGRES_PASSWORD: msdelivery-db-pass
    POSTGRES_DB: delivery
  port: 5432