apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-{{ .Release.Name }}-service"
  labels:
    app: "{{ .Chart.Name }}-{{ .Release.Name }}-service"
spec:
  selector:
    app: "{{ .Chart.Name }}-{{ .Release.Name }}"
  ports:
    {{- range .Values.service.ports }}
    - port: {{ .port }}
      name: {{ .name }}
      protocol: TCP
      targetPort: {{ .targetPort }}
    {{- end}}
  type: NodePort
