apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: "{{ .Chart.Name }}-{{ .Release.Name }}-service-monitor"
  labels:
    release: app
spec:
  selector:
    matchLabels:
      app: "{{ .Chart.Name }}-{{ .Release.Name }}-service"
  endpoints:
  {{- range .Values.serviceMonitor.endpoints }}
    - port: {{ .port }}
      scheme: http
      path: {{ .path }}
      interval: {{ .interval }}
    {{- end}}