apiVersion: v2
name: homework-5-chart
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: postgres
    repository: file://./charts/postgres
    version: 0.1.0
  - name: kube-prometheus-stack
    repository: https://prometheus-community.github.io/helm-charts
    version: 45.9.1
  - name: ingress-nginx
    repository: https://kubernetes.github.io/ingress-nginx/
    version: 4.7.1