apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
data:
  postgresDb      : cG9zdGdyZXM=
  postgresUser    : YWRtaW4=
  postgresPassword: YWRtaW4=
  artemisUsername : dXNlcg==
  artemisPassword : dXNlcg==