version: "3"

services:
  postgres:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=auth_user
      - POSTGRES_PASSWORD=auth_pass
      - POSTGRES_DB=auth
  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"