apiVersion: v2
name: ms-auth
description: auth microservice
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: postgres
    repository: file://./charts/postgres
    version: 0.1.0
  - name: redis
    repository: file://./charts/redis
    version: 0.1.0
