application:
  destinationSend: notice-order
  destinationListener: order-notice
server:
  port: 8003
spring:
  application:
    name: app-notice
  artemis:
    mode: native
    broker-url: tcp://localhost:61616
    user: user
    password: user
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true