version: "3"

services:
  postgres:
    image: postgres:11
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=inventory_user
      - POSTGRES_PASSWORD=inventory_pass
      - POSTGRES_DB=inventory